### PR TITLE
Added support https requests and follow redirects

### PR DESCRIPTION
**Pull request by razvan-sv**
Hi Bruno,

I recently stumbled on your gem, gave it a shot and noticed there's not HTTPS support.
Added it since I need it for my project. Updated the tests and README as well.

Also added logic to follow GET redirects. Limited the number to 3.

Thanks,
Razvan.

### CODE REVIEW

**Comment by brunogh** [comment]
Awesome Razvan!

Merging! Thanks!

:beers: :beers:

**Comment by funkyboy** [comment]
HI there,

I am setting a different value for redirects, like this

`Tor::HTTP.redirects_count = 10`

then I call 

`res = Tor::HTTP.get("check.torproject.org", '/', 80)`

and if I check redirects_count after the GET call I see it's back to 3

`Tor::HTTP.redirects_count` 
=> 3

Any idea why?

**Comment by razvan-sv** [comment]
Hi,

Currently the redirect count is not configurable. I'll update it soon.

**Comment by funkyboy** [comment]
Ok, thanks!

**Comment by razvan-sv** [comment]
Done. Please checkout PR [#6](https://github.com/brunogh/tor_requests/pull/6). You can use my fork if you want, until the PR gets merged.

**Pull request merged**
